[phases.setup]
nixPkgs = ["...", "php83", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.curl", "php83Extensions.zip", "php83Extensions.gd", "php83Extensions.bcmath", "php83Extensions.tokenizer", "php83Extensions.fileinfo", "php83Extensions.ctype", "php83Extensions.openssl", "nodejs_18"]

[phases.install]
cmds = [
    "mkdir -p /etc/nix",
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
